[project]
name = "bayesian-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "matplotlib>=3.9.2",
    "optuna>=4.0.0",
    "polars>=1.8.2",
    "ruff>=0.6.8",
]
